export const tosinPictures = [
  {
    src: "../../../assets/1.jpeg",
    name: "Bonita",
    widthSpan: "w-2",
    heightSpan: "h-3",
  },
  {
    src: "../../../assets/11.jpeg",
    name: "Lemon Drop",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/12.jpeg",
    name: "Mi Amor",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/13.jpeg",
    name: "Mi Tesoro",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/14.jpeg",
    name: "Mi Cielo",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/15.jpeg",
    name: "Peachy",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/16.jpeg",
    name: "Strawberry",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/17.jpeg",
    name: "Irreplaceable Queen",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/18.jpeg",
    name: "Sun Flower",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/19.jpeg",
    name: "Sunshine",
    widthSpan: "",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/20.jpeg",
    name: "Goddess",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/22.jpeg",
    name: "Wifey",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/21.jpeg",
    name: "Trap Queen",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },

  {
    src: "../../../assets/23.jpeg",
    name: "Sunshine",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/24.jpeg",
    name: "Sugar",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },

  {
    src: "../../../assets/26.jpeg",
    name: "Pumpkin",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/27.jpeg",
    name: "Smiley",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/28.jpeg",
    name: "Mon cheri",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/29.jpeg",
    name: "World Best",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/30.jpeg",
    name: "All in one",
    widthSpan: "w-3",
    heightSpan: "h-3",
  },
  {
    src: "../../../assets/25.jpeg",
    name: "Sweet Momma",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/31.jpeg",
    name: "Mi Tesoro",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/35.jpeg",
    name: "Most Complete",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/2.jpeg",
    name: "Boo",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/32.jpeg",
    name: "Little Bird",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/3.jpeg",
    name: "Bootylicious",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/4.jpeg",
    name: "Bae",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/33.jpeg",
    name: "Brown Sugar",
    widthSpan: "h-2",
    heightSpan: "w-2",
  },
  {
    src: "../../../assets/5.jpeg",
    name: "ButterFly",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/6.jpeg",
    name: "Candy",
    widthSpan: "",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/34.jpeg",
    name: "Irreplaceable",
    widthSpan: "w-2",
    heightSpan: "h-3",
  },
  {
    src: "../../../assets/7.jpeg",
    name: "Cutie",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/8.jpeg",
    name: "CutiePie",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/9.jpeg",
    name: "Honey",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/10.jpeg",
    name: "Lovey",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/36.jpeg",
    name: "Life Partner",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/37.jpeg",
    name: "Heaven sent",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/38.jpeg",
    name: "Pearli",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/50.jpeg",
    name: "Apple",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/39.jpeg",
    name: "Pearlsi",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/41.jpeg",
    name: "Cookie",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/42.jpeg",
    name: "Everywhere Stew",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/44.jpeg",
    name: "Sugar Bomb",
    widthSpan: "w-2",
    heightSpan: "h-3",
  },
  {
    src: "../../../assets/45.jpeg",
    name: "D light",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/46.jpeg",
    name: "Butter Scotch",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/40.jpeg",
    name: "Butter Finger",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },

  {
    src: "../../../assets/48.jpeg",
    name: "Peach",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/49.jpeg",
    name: "Cherry",
    widthSpan: "",
    heightSpan: "",
  },


  {
    src: "../../../assets/52.jpeg",
    name: "Baby gril",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/51.jpeg",
    name: "Honeycrisp",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/53.jpeg",
    name: "Babe",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/54.jpeg",
    name: "Babykins",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/43.jpeg",
    name: "Sugar Nova",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/47.jpeg",
    name: "Berry Boo",
    widthSpan: "",
    heightSpan: "",
  },
];
