export const harrisonPictures = [
  {
    src: "../../../assets/h8.jpeg",
    name: "Prince Charming",
    widthSpan: "w-2",
    heightSpan: "h-3",
  },

  {
    src: "../../../assets/h2.jpeg",
    name: "Saeedi",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h3.jpeg",
    name: "Sailor",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h4.jpeg",
    name: "Mi Tesoro",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h5.jpeg",
    name: "Mi Cielo",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h1.jpeg",
    name: "Rum rum",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/h9.jpeg",
    name: "Papito",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h10.jpeg",
    name: "Paradise",
    widthSpan: "",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h11.jpeg",
    name: "Lover",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h13.jpeg",
    name: "Lover Pie",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h12.jpeg",
    name: "Flower",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },

  {
    src: "../../../assets/h14.jpeg",
    name: "Fruit cake",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h6.jpeg",
    name: "Prince",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h15.jpeg",
    name: "Sugar",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },

  {
    src: "../../../assets/h16.jpeg",
    name: "Flame",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h17.jpeg",
    name: "Gangstar baby",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h18.jpeg",
    name: "Mon cheri",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h19.jpeg",
    name: "World Best",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h20.jpeg",
    name: "All in one",
    widthSpan: "h-2",
    heightSpan: "w-2",
  },

  {
    src: "../../../assets/h21.jpeg",
    name: "Everything",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h7.jpeg",
    name: "Papi",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h22.jpeg",
    name: "Luv",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/h24.jpeg",
    name: "Boo",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/h26.jpeg",
    name: "Mi Amor",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h27.jpeg",
    name: "Bae",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h28.jpeg",
    name: "yellow Sugar",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h29.jpeg",
    name: "Kissy Face",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/h32.jpeg",
    name: "Cutie",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h33.jpeg",
    name: "Key to my heart",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h25.jpeg",
    name: "Popsicle",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h55.jpeg",
    name: "Life Partner",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h34.jpeg",
    name: "My Guy",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h35.jpeg",
    name: "Baby Boo",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h46.jpeg",
    name: "Rocky",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h36.jpeg",
    name: "Hero",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h30.jpeg",
    name: "Hon'",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h37.jpeg",
    name: "Gorgeous",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h49.jpeg",
    name: "Hot Shot",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h38.jpeg",
    name: "Knight in Shiny Aemor",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h39.jpeg",
    name: "Star",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h23.jpeg",
    name: "Most Complete",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h40.jpeg",
    name: "One and Only",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h41.jpeg",
    name: "Cherry Pie",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h42.jpeg",
    name: "Handsome",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h43.jpeg",
    name: "Handsome Boo",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h44.jpeg",
    name: "Handsome Bobo",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h45.jpeg",
    name: "Sparky",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/h47.jpeg",
    name: "Honey Bear",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h48.jpeg",
    name: "King",
    widthSpan: "",
    heightSpan: "",
  },

  {
    src: "../../../assets/h50.jpeg",
    name: "Butter Cup",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
  {
    src: "../../../assets/h52.jpeg",
    name: "Champ",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h53.jpeg",
    name: "Other Half",
    widthSpan: "",
    heightSpan: "",
  },
  {
    src: "../../../assets/h54.jpeg",
    name: "Sunshine",
    widthSpan: "w-2",
    heightSpan: "h-2",
  },
];
